### PR TITLE
Updated Makefile

### PR DESCRIPTION
**Pull request by proyectoscott**
Trying to build ble example was failing replaced configuration with working blinky build makefile style

### CODE REVIEW

**Comment by proyectoscott** [comment]
This is my first time committing to git, have cloned a bunch, so if I messed it up let me know how please.

**Comment by proyectoscott** [comment]
Well that was one.

**Comment by oclyke** [comment]
@proyectoscott Thanks for taking the time to submit this PR! I don't see any problems with the PR itself - your commit is simple and your message about it is pretty clear. I am a little confused about what the problem was so in the future that would be helpful to know. 

I just confirmed the error you were having
```
root@26a8cdb2f1b8:/app/AmbiqSuiteSDK/boards_sfe/redboard_artemis/examples/ble_cordio_tag/gcc# make asb
Makefile:110: warning: you have not defined COM_PORT. Assuming it is COM4
Makefile:114: warning: you have not defined PYTHON3. assuming it is accessible by 'python3'
Makefile:118: defaulting to 115200 baud for ASB
Makefile:122: defaulting to 921600 baud for SVL
Makefile:143: warning: you have not defined BOARDPATH so will continue assuming that the BOARD root is at ../../..
Makefile:151: warning: you have not defined PROJECTPATH so will continue assuming that the PROJECT root is at ..
Makefile:160: CONFIG is set to: ../gcc/bin
 Compiling gcc /app/AmbiqSuiteSDK/third_party/exactle/sw/stack/hci/hci_main.c
/app/AmbiqSuiteSDK/third_party/exactle/sw/stack/hci/hci_main.c:124:1: fatal error: opening dependency file ../gcc/bin/hci_main.d: No such file or directory
 }
 ^
compilation terminated.
Makefile:435: recipe for target '../gcc/bin/hci_main.o' failed
make: *** [../gcc/bin/hci_main.o] Error 1
```

This is because, for some reason, the bin directory is not being created. If you first run ```mkdir``` using the value that ```CONFIG``` is assigned (i.e. ```mkdir -p ../gcc/bin```) then compilation works. 

Your solution also works - in fact all that is needed is to set ```CONFIG``` to 'bin'. However the intention was to make this makefile callable from a remote location and make sure the built executable stays associated with the project. 

There are a few other solutions that keep everything relative to the project:

1. Add ```$(CONFIG)``` to the list of phony targets
2. Remove the ```$(CONFIG)``` target and simply place the required command under the ```directories``` target (which is phony so it will always run. 

I'm still a little confused as to why the ```$(CONFIG)``` target was not activated when the directory did not exist...

**Comment by oclyke** [comment]
Great, those changes seem to have done the trick. I appreciate the help Happy new year!

**Pull request merged**
