### PR TITLE
Itm Alternatives

### PR DESCRIPTION
**Pull request by oclyke**
A possible improvement to address #19 

Please try it out and discuss.

### CODE REVIEW

**Comment by MrOneTwo** [comment]
Unfortunately no luck. Doesn't output anything. Testing with `JLinkSWOViewer -device AMA3B1KK-KBR -cpufreq 48000000` via *Segger JLink Edu Mini*.

Here is the code snippet I use to test (it cuts out before not important bits):

```C
int
main(void)
{
  am_util_id_t sIdDevice;
  uint32_t ui32StrBuf;

  // Set the clock frequency.
  am_hal_clkgen_control(AM_HAL_CLKGEN_CONTROL_SYSCLK_MAX, 0);

  // Set the default cache configuration
  am_hal_cachectrl_config(&am_hal_cachectrl_defaults);
  am_hal_cachectrl_enable();

#ifndef NOFPU
  am_hal_sysctrl_fpu_enable();
  am_hal_sysctrl_fpu_stacking_enable(true);
#else
  am_hal_sysctrl_fpu_disable();
#endif

  // Configure the board for low power operation.
  am_bsp_low_power_init();

  am_bsp_itm_printf_enable();
  am_bsp_itm_string_print("Test...");

  am_util_debug_printf(" >> Booting the CPU...\r\n");

```

**Comment by oclyke** [comment]
@MrOneTwo I tried this and got it working using the GUI interface to the SWO viewer. 

Where do you configure the baud rate? When using the GUI you are first prompted to supply the device, core frequency and **baud rate** which I don't see in your command. If you are using the branch for this PR then I have set the default ITM/SWO frequency to 2M baud (2000 khz). 
GUI_prompt


I'm probably stating the obvious but opening the ITM/SWO connection does not cause a board reset so you may need to manually press the reset button to get text to show up.
SWO_operation

**Comment by MrOneTwo** [comment]
@oclyke Great! Nice it works. I'm gonna test it later today with setting the SWO frequency. I'm using CLI version of SWO Viewer on Linux. Also I've read this in the JLink documentation:

> Usually not necessary to define since optimal SWO speed is calculated automaticallybased on the CPU frequency and the capabilities of the connected J-Link. 

Anyway, thank you!

**Comment by oclyke** [comment]
Sweet! That's an interesting bit about the speed too -- let us know what you find out.

**Pull request merged**
